### ISSUE TITLE
default "set send timeout policy"  should not set a timeout of 0

### ISSUE THREAD

**Issue by betzrhodes** [electricimp/ConnectionManager#6]
The set send timeout policy should not be set this way in the constructor.  Docs state timeout should not be set to 0. 

line 45 - server.setsendtimeoutpolicy(RETURN_ON_ERROR, WAIT_TIL_SENT, 0);

**Comment by betzrhodes** [comment]
ImpPager is using a default timeout of 1.

**Comment by ppetrosh** [comment]
Fixed on master
